import React, { useState } from 'react'
import { Outlet, Navigate, useLocation } from 'react-router-dom'
import Sidebar from './Sidebar.jsx'
import Header from './Header.jsx'
import BottomNav, { MobileDrawer } from './MobileNav.jsx'
import ToastHost from '../common/ToastHost.jsx'
import Chatbot from '../chatbot/Chatbot.jsx'
import ErrorBoundary from '../common/ErrorBoundary.jsx'
import { useApp } from '../../context/AppContext.jsx'
import { getStoredAuth } from '../../utils/authStorage.js'

const TITLES = {
  '/animals': ['Animal Health Monitoring', 'Monitor individual animal health and mastitis risk.'],
  '/forecast': ['Mastitis Forecasting Engine', 'AI-powered prediction before clinical symptoms appear.'],
  '/alerts': ['Alert Center', 'Every early warning generated by the prediction engine.'],
  '/recommendations': ['Recommended Actions', 'Prioritised, animal-specific preventive care.'],
  '/analytics': ['Herd Analytics', 'Trends and correlations across the herd.'],
  '/iot': ['Live Farm Sensors', 'Wearables, milk sensors and environmental monitoring.'],
  '/map': ['Mastitis Risk Map', 'Farm locations across the region.'],
  '/settings': ['Farm Settings', null],
}

export default function AppLayout() {
  const { auth } = useApp()
  const [drawerOpen, setDrawerOpen] = useState(false)
  const location = useLocation()

  // Check both context auth and synchronous storage to eliminate redirect bouncing during state propagation
  const isAuthed = auth.isLoggedIn || !!getStoredAuth()?.isLoggedIn

  if (!isAuthed) return <Navigate to="/login" replace />

  const match = Object.keys(TITLES).find((k) => location.pathname === k)
  const [title, subtitle] = match ? TITLES[match] : [null, null]

  return (
    <div className="min-h-screen bg-canvas">
      <Sidebar />
      <MobileDrawer open={drawerOpen} onClose={() => setDrawerOpen(false)} />
      <div className="lg:pl-[236px]">
        <Header onOpenMobileNav={() => setDrawerOpen(true)} title={title} subtitle={subtitle} />
        <main className="mx-auto max-w-[1400px] px-4 pb-20 pt-5 sm:px-6 sm:pb-8 lg:px-8">
          <ErrorBoundary>
            <Outlet />
          </ErrorBoundary>
        </main>
      </div>
      <BottomNav />
      <ToastHost />
      <Chatbot />
    </div>
  )
}
